apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    io.kompose.service: mysql
  {{- include "users.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.type }}
  selector:
    io.kompose.service: mysql
    {{- include "users.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.mysql.ports | toYaml | nindent 2 }}
