apiVersion: v1
kind: Service
metadata:
  name: users-app
  labels:
    io.kompose.service: users-app
  {{- include "users.labels" . | nindent 4 }}
spec:
  type: {{ .Values.usersApp.type }}
  selector:
    io.kompose.service: users-app
    {{- include "users.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.usersApp.ports | toYaml | nindent 2 }}
