apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app
  labels:
    io.kompose.service: users-app
  {{- include "users.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.usersApp.replicas }}
  selector:
    matchLabels:
      io.kompose.service: users-app
    {{- include "users.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.service: users-app
      {{- include "users.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: BACKEND_PORT
          value: {{ quote .Values.usersApp.usersApp.env.backendPort }}
        - name: DATABASE_URL
          value: {{ quote .Values.usersApp.usersApp.env.databaseUrl }}
        - name: DEFAULT_PASSWORD
          value: {{ quote .Values.usersApp.usersApp.env.defaultPassword }}
        - name: DEFAULT_USER
          value: {{ quote .Values.usersApp.usersApp.env.defaultUser }}
        - name: JWT_SECRET
          value: {{ quote .Values.usersApp.usersApp.env.jwtSecret }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.usersApp.usersApp.image.repository }}:{{ .Values.usersApp.usersApp.image.tag
          | default .Chart.AppVersion }}
        name: users-app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
      initContainers:
      - command:
        - sh
        - -c
        - until mysqladmin ping -h "$MYSQL_HOST" --silent; do echo "Waiting for MySQL...";
          sleep 2; done
        env:
        - name: MYSQL_HOST
          value: {{ quote .Values.usersApp.waitForMysql.env.mysqlHost }}
        - name: MYSQL_USER
          value: {{ quote .Values.usersApp.waitForMysql.env.mysqlUser }}
        - name: MYSQL_PASSWORD
          value: {{ quote .Values.usersApp.waitForMysql.env.mysqlPassword }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.usersApp.waitForMysql.image.repository }}:{{ .Values.usersApp.waitForMysql.image.tag
          | default .Chart.AppVersion }}
        name: wait-for-mysql
        resources: {}
      restartPolicy: Always
      imagePullPolicy: Always