pipeline {
    agent any

    environment {
        CONTAINER_NAME="example-frontend-container"
        LOCAL_IMAGE_NAME="exampleimage/${BUILD_TAG}"
    }

    stages {
        stage('Initialize'){
            echo "Container name: ${env.CONTAINER_NAME}"
			echo "Local image name: ${env.LOCAL_IMAGE_NAME}"
			echo "Git branch: ${env.BRANCH_NAME}"
        }


        stage('Cloning Git repo') {
            steps {
                // Cloning from Gitlab
                git branch:'main', url: 'git@gitlabe1.ext.net.nokia.com:ntas-summer-program-2024/users-example-app.git', credentialsId: 'jenkins-key-nagytoth-wsl'
            }
        }


        stage('Compile frontend') {
            steps {
                nodejs(nodeJSInstallationName: 'node') {
                    sh 'npm --version'
                    sh 'npm install && CI=false npm run build'
                }
            }
        }        

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building image with local ID ${env.LOCAL_IMAGE_NAME}:latest"
                    def dockerImage = docker.build("${env.LOCAL_IMAGE_NAME}:latest")            
                }
            }
        }

        // stage('Push docker image'){
        //     steps{
        //         script{
        //             docker.push()
        //         }
        //     }
        // }

        // stage('Cleanup'){
        //     sh "docker rmi -f ${env.LOCAL_IMAGE_NAME}:latest"
        // }
    }

    post {
        success {
            echo 'Pipeline completed!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
