pipeline {
    agent any

    environment {
        CONTAINER_NAME="pue-frontend-container"
        LOCAL_IMAGE_NAME="pue-frontend/${BUILD_TAG}"
    }

    stages {
        stage('Initialize'){
            steps{
                echo "Container name: ${env.CONTAINER_NAME}"
                echo "Local image name: ${env.LOCAL_IMAGE_NAME}"
                echo "Git branch: ${env.BRANCH_NAME}"
            }
        }

        stage('Compile frontend') {
            steps {
                nodejs(nodeJSInstallationName: 'node') {
                    sh 'npm --version'
                    sh 'npm install && CI=false npm run build'
                }
            }
        }        

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building image with local ID ${env.LOCAL_IMAGE_NAME}:latest"
                    def dockerImage = docker.build("${env.LOCAL_IMAGE_NAME}:latest")            
                }
            }
        }

        // stage('Push docker image'){
        //     steps{
        //         script{
        //             docker.push()
        //         }
        //     }
        // }

        // stage('Cleanup'){
        //     sh "docker rmi -f ${env.LOCAL_IMAGE_NAME}:latest"
        // }
    }

    post {
        success {
            echo 'Pipeline completed!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
