services:
  mysql: # database service
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes: # Mounting the host directory ~/mysql_data to /var/lib/mysql in the container (otherwise when container was removed, normally /var/lib/mysql would be removed as well -> data loss)
      # - ~/mysql_data:/var/lib/mysql
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
  users-app: # backend/API service + frontend static file hosting
    restart: always
    container_name: users-app
    image: users-app
    build:
      context: .
    depends_on: # dependency order: mysqldb should start BEFORE backend
      - mysql
    environment: # define environment variables
      - DATABASE_URL=mysql://myuser:mypassword@mysql:3306/userdb
      - BACKEND_PORT=3000
      - JWT_SECRET="jSI4ldmUR0Wag9MEJlmbSpqslrfT8NquO7sxmVVc4URR95o52wHyyduZMkLz3wojiH6+99LZyg24vTkPFKZm4Z2/tNceJmCD7F24exW+WgqIMtRqwc3Cdwt39+Yh6DHLAHyJ73loJ/4V8AHpvSPKWh8fO9fLxdKh0XIXOQC+KIIC20Kjgs5EncfYfO41yac2XZk7ERwq3gbCVnm4g9irwUxWFWhUpFwgXJeGHsdOrnE9bipBVPAKHjo/Bt432h4OVEKMJ8KCLJuzXISAMgrrUImeRyag31KKUACDdjXAkGut/fS0noj9jQqZjJYZSUsUaDWqBaNNlN10v/B71g9FfA=="
      - DEFAULT_USER=root
      - DEFAULT_PASSWORD=root
    ports:
      - 3000:3000
volumes:
  mysql-data:
