POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "root"
}

###


GET http://localhost:3000/users/filter HTTP/1.1
content-type: application/json